Feature/seab 2928/circleci audit (#1396)
* Compare npm audit results between PR and develop using circleci
https://ucsc-cgl.atlassian.net/browse/SEAB-2928

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -84,6 +84,45 @@ jobs:
           failure_message: Nightly << parameters.stack >> auth tests failed!
           webhook: $SLACK_WEBHOOK
 
+  audit:
+    working_directory: ~/repo
+    docker:
+      - image: cimg/base:stable-20.04
+        auth:
+          username: dockstoretestuser
+          password: $DOCKERHUB_PASSWORD
+    steps:
+      - browser-tools/install-browser-tools
+      - checkout
+      - run:
+          name: Checkout merge commit (PRs only)
+          command: |
+            if [[ -n "${CIRCLE_PULL_REQUEST}" ]]
+            then
+              git fetch origin +refs/pull/${CIRCLE_PULL_REQUEST##*/}/merge:
+              git checkout -qf FETCH_HEAD
+            fi
+      - install_container_dependencies
+      - run:
+          name: Run npm audit
+          # Run npm audit on current branch and compare it with the results of running npm audit on the develop branch. If there are more
+          # high or critical findings, then the test fails (Test is optional)
+          command: |
+            bash -i -c "npm ci"
+            bash -i -c "npm audit > vulnerabilities.txt" || true
+            bash scripts/npm-audit.sh
+            git stash
+            git checkout develop
+            bash -i -c 'npm ci'
+            bash -i -c 'npm audit > vulnerabilities.txt' || true
+            # Remove wget once these scripts have been merged to develop
+            if [[ ! -f scripts/npm-audit.sh ]]; then
+              wget -O scripts/npm-audit.sh https://raw.githubusercontent.com/dockstore/dockstore-ui2/4b885b51c3fdc1b0faa6450c20e919587bb3f665/scripts/npm-audit.sh
+              wget -O scripts/compare-num-vulns.sh https://raw.githubusercontent.com/dockstore/dockstore-ui2/4b885b51c3fdc1b0faa6450c20e919587bb3f665/scripts/compare-num-vulns.sh
+            fi
+            bash scripts/npm-audit.sh
+            bash scripts/compare-num-vulns.sh
+
   lint_license_unit_test_coverage:
     working_directory: ~/repo
     docker:
@@ -254,6 +293,12 @@ workflows:
   everything:
     jobs:
 #      # Add the tags filter to all jobs so they will run before upload_to_s3
+      - audit:
+        filters:
+          tags:
+            only: /.*/
+          context:
+            - dockerhub
       - lint_license_unit_test_coverage:
           filters:
             tags:
